export const REGISTER_CUSTOMER="REGISTER_USER" ; 
export const REGISTER_THEATER ="REGISTER_THEATER"
export const REGISTER_ADMIN= "REGISTER_ADMIN"
export const LOGIN_USER="LOGIN_USER" ; 
export const LOGOUT ="LOGOUT" ; 
export const LOAD_USER="LOAD_USER"
export const ADD_ROOM="ADD_ROOM" ; 
export const GET_ROOMS="GET_ROOMS" ; 
export const DELETE_ROOM= "DELETE_ROOM" ; 
export const EDIT_ROOM="EDIT_ROOM" ; 